// These tests were generated by AI.

import { toQueryString } from "../../utils/query-string";

describe("toQueryString", () => {
  it("should convert object to query string", () => {
    const result = toQueryString({ foo: "bar", baz: "qux" });
    expect(result).toBe("foo=bar&baz=qux");
  });

  it("should skip null and undefined values", () => {
    const result = toQueryString({ foo: "bar", baz: null, qux: undefined });
    expect(result).toBe("foo=bar");
  });

  it("should encode special characters", () => {
    const result = toQueryString({ "a b": "c&d" });
    expect(result).toBe("a%20b=c%26d");
  });

  it("should return empty string for empty object", () => {
    const result = toQueryString({});
    expect(result).toBe("");
  });

  it("should handle numeric and boolean values", () => {
    const result = toQueryString({ num: 42, bool: true });
    expect(result).toBe("num=42&bool=true");
  });
});
